export const categories = [
  "Accounting",
  "Adminstration/Operations",
  "Agriculture and Agribusiness",
  "Clothing and Dress Making",
  "Creative & Design",
  "Customer Service & Call Centre",
  "Education & Training",
  "Engineering & Construction",
  "Government",
  "Healthcare & Pharmaceutical",
  "Hospitality",
  "Human Resources",
  "Insurance",
  "IT & Telecoms",
  "Manufacturing",
  "Marketing, Media & Brand",
  "Mining & Natural Resources",
  "NGO,Community & Social Development",
  "Office & Admin",
  "Other",
  "Project/Programme Management",
  "Real Estate",
  "Research, Science & Biotech",
  "Retail",
  "Sales",
  "Security",
  "Strategy & Consulting",
  "Tourism & Travel",
  "Trades & Services",
  "Transport & Logistics",
];
